COMPONENTS = \
	components/button.css \
	components/form.css \
	components/input.css \
	components/menu.css \
	components/message.css \
	components/site.css \
	components/reset.css

# see: hand commented lines by lupan

semantic.css: $(COMPONENTS)
	cat $(COMPONENTS) > semantic.css
